<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
    $_optionHelper = $this->helper('Codazon\DynamicRow\Helper\Data');
    $subs = $_optionHelper->getConfig('dynamic_row/general/dynamic_field');
    $dataSub = json_decode($subs,true);
    $initSubject = [
        "1" => [
            "subject" => "Sales & product consulting",
            "value_subject" => "forsaljning@vesani.se"
        ],
        "2" => [
            "subject" => "Complaints & Regrets",
            "value_subject" => "reklamation@vesani.se"
        ],
        "3" => [
            "subject" => "Delivery & Transport",
            "value_subject" => "logistik@vesani.se"
        ],
        "4" => [
            "subject" => "Invoice & Finance",
            "value_subject" => "ekonomi@vesani.se"
        ]
    ];
?>
<form class="form contact"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Write Us') ?></span></legend><br />
        <div class="field note no-label"><?php /* @escapeNotVerified */ echo __('Jot us a note and we’ll get back to you as quickly as possible.') ?></div>
        <!-- Custom field -->
        <div class="field subject required">
            <div class="control">
                <?php
                    $dataOptions = count($dataSub) === 0 ? $initSubject : $dataSub;
                ?>
                <select id="subject">
                    <option value="">Select an option&hellip;</option>
                    <?php foreach ($dataOptions as $data) : ?>
                        <option value="subject1"><?php echo $data['value_subject'] ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="field name required">
            <div class="control">
                <input placeholder="<?php /* @escapeNotVerified */ echo __('Name') ?>" name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <div class="control">
                <input placeholder="<?php /* @escapeNotVerified */ echo __('Email') ?>" name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field telephone">
            <div class="control">
                <input placeholder="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="" class="input-text" type="text" />
            </div>
        </div>
        <div class="field comment required">
            <div class="control">
                <textarea placeholder="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>
