<div class="customer-welcome">
    <button
        data-mage-init='{"dropdown":{}}'
        data-toggle="dropdown"
        class="action btn-mypage-desktop"
        data-action="customer-menu-toggle">
        <span><?= $block->escapeHtml(__('My pages')) ?></span>
    </button>
    <ul data-target="dropdown" class="dropdown-options">
        <?php
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $customerSession = $objectManager->create("Magento\Customer\Model\Session");
        ?>
        <?php if($customerSession->isLoggedIn()): ?>
            <li>
                <a href="<?php echo $this->getUrl("customer/account") ?>" class="my-account">
                    <?php /* @escapeNotVerified */ echo __('My Account') ?>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->getUrl("customer/account/logout") ?>" class="my-account">
                    <?php /* @escapeNotVerified */ echo __('Logout') ?>
                </a>
            </li>
        <?php else: ?>
            <li>
                <a href="<?php echo $this->getUrl("customer/account/login") ?>" class="login">
                    <?php /* @escapeNotVerified */ echo __('Login') ?>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->getUrl('customer/account/create') ?>" class="register">
                    <?php /* @escapeNotVerified */ echo __('Create an Account') ?>
                </a>
            </li>
        <?php endif; ?>
        <li>
            <span data-bind="scope: 'wishlist'" class="link wishlist">
                <a href="<?php echo $this->getUrl('wishlist') ?>">
                    <?php echo __('Wish List') ?>
                    <!-- ko if: wishlist().counter -->
                        <span data-bind="text: wishlist().counter" class="counter qty"></span>
                    <!-- /ko -->
                </a>
            </span>
        </li>   
    </ul>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }
</script>

