<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_AbTesting
 * @author    Webkul
 * @copyright Copyright (c)Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$trackTypes = $block->trackTypesOption();
$currentTestId = $block->getCurrentTestId();
$trackUrl = $block->getUrl('abtesting/tracktypes/loadtracktypes');
$goalBaseUrl = $block->getUrl('abtesting/abtest/showgoalsajax');
$goalBaseDeleteUrl = $block->getUrl('abtesting/abtest/deletegoals');
?>
<input type="hidden" id="track_base_url" name="track_url" value="<?= /* @noEscape */ $trackUrl?>"/>
<input type="hidden" id="goal_base_url" name="goal_base_url" value="<?= /* @noEscape */$goalBaseUrl?>"/>
<div class='wk-goals-div'>
<div class="note" data-role="goals-create-info">
                <?= /* @noEscape */ $block->escapeHtml(__('Set goals means,
                what will happen if your assumptions work'));?>
</div>
<div class="product-create-configuration-action">
                <button type="button" data-action="open-steps-wizard" title="Create Product Configurations"
                        class="action-secondary abtest-goals" data-bind="click: open">
                <span data-role="button-label"
                data-edit-label="<?= /* @noEscape */$block->escapeHtmlAttr(__('Add Goals')) ?>">
                    <?= /* @noEscape */__('Add Goals')
                    ?>
                </span>
                </button>
            </div>
</div>
<?= /* @noEscape */ $block->getGridHtml(); ?>
<div class="callfor-popup">
<div id="wk-goals-block">
<div class="fieldset-wrapper">
    <div class="fieldset fieldset-wrapper-title">
           <strong> <span><?= /* @escapeNotVerified */ $block->escapeHtml(__('Goals Information')) ?></span></strong>
    </div>
</div>
<form  name = "create-goals-form" action = "<?= /* @noEscape */ $block->getUrl('abtesting/abtest/goalssave')?>"
class="create-goals" method="post"
 id="create-goals" data-mage-init='{"validation": {}}' enctype="multipart/form-data">
    <input type="hidden" id= "edit_goal_id" name="edit_goal_id" value=""/>
    <input type="hidden" name="test_id" value="<?= /* @noEscape */ $currentTestId;?>"/>
    <p class="message no-display" data-message></p>
    <div class='admin__fieldset-wrapper-content'>
        <fieldset class="admin__fieldset">
            <div class="admin__field required">
                <div class="admin__field-label">
                    <label><span><?=  /* @noEscape */__('Goal Name')?></span></label>
                </div>
                <div class="admin__field-control">
                <input class="admin__control-text" type="text" name="goal_name" id="goal_name"
                placeholder= "<?= /* @noEscape */__('Enter Goal Name')?>"
                data-validate="{required:true,
                    'validate-no-html-tags':true,'validate-no-html-tags':true}" aria-required="true"
/>
                </div>
            </div>
            <div class="admin__field wkgoaldescription">
                <div class="admin__field-label">
                    <label><span><?= /* @noEscape */__('Goal Description')?></span></label>
                </div>
                <div class="admin__field-control">
                    <textarea class="admin__control-textarea" type="text" name="goal_description"
                    placeholder="<?= /* @noEscape */ __('Goal Description')?>" id="goal_description"
                    data-validate="{'validate-no-html-tags':true}" aria-required="true"
 > </textarea>
                </div>
            </div>
            <div class="admin__field required wktracktypes">
                <div class="admin__field-label">
                    <label><span><?=  /* @noEscape */__('Track Types')?></span></label>
                </div>
                <div class="admin__field-control">
                    <select class="admin__control-select" id="wk-track-type" name = 'track_type_id'
                    data-validate="{required:true,
                    'validate-no-html-tags':true}" aria-required="true"
>                   
                    <?php foreach ($trackTypes as $key => $tracks) {?>
                        <option value = "<?=  /* @noEscape */$tracks['value']?>">
                            <?= /* @noEscape */ __($tracks['label'])?></option>
                        <?php }?>
                    </select>
                </div>
            </div>
            <div class="admin__field required wk-tracks">
                <div class="admin__field-label">
                    <label><span><?= /* @noEscape */ __('Tracks')?></span></label>
                </div>
                <div class="admin__field-control">
                    <select class="admin__control-select tracks" id="tracks" data-validate="{required:true,
                    'validate-no-html-tags':true}" aria-required="true"
                        name = 'tracks'>
                            <option value = ""><?= /* @noEscape */__('Select Track Options')?></option>
                    </select>
                </div>
            </div>
            <div class="admin__field required wktrackcond no-display">
                <div class="admin__field-label">
                    <label><span><?= /* @noEscape */ __('Condition')?></span></label>
                </div>
                <div class="admin__field-control">
                    <select class="admin__control-select" data-validate="{required:true,
                    'validate-no-html-tags':true}" name="conditions" id="conditions" aria-required="true"
name = 'conditions'>
                        <option value = "matches"><?=  /* @noEscape */ __('Matches')?></option>
                        <option value = "like"><?=  /* @noEscape */ __('Like')?></option>
                    </select>
                </div>
            </div>
            <div class="admin__field required wktrackurl no-display">
                <div class="admin__field-label">
                    <label><span><?= /* @noEscape */ __('Url')?></span></label>
                </div>
                <div class="admin__field-control">
                <input class="admin__control-text" id="url" name= "url" data-validate="{required:true,
                    'validate-no-html-tags':true,'validate-url': true}" aria-required="true"
 type="text" name="url" placeholder= "<?= /* @noEscape */ __('Enter Url')?>"/>
                </div>
            </div>
            <div class="admin__field required no-display wkcssselector">
                <div class="admin__field-label">
                    <label><span><?= /* @noEscape */ __('Add Css selector')?></span></label>
                </div>
                <div class="admin__field-control">
                <input id= "css_property" class="admin__control-text" data-validate="{required:true,
                    'validate-no-html-tags':true}" name="css_property" aria-required="true"
 type="text" placeholder= "<?= /* @noEscape */ __('Enter Css selector')?>"/>
                </div>
            </div>
        </fieldset>
    </div>
</form>
</div>

</div>
<script type="text/x-magento-init">
    {
        "#create-goals": {
            "validation": {}
        }
    }
</script>
<script>
   require(
       [
           'jquery',
           'Magento_Ui/js/modal/modal',
           'Magento_Ui/js/modal/alert',
           'Magento_Ui/js/modal/confirm',
           'mage/mage'
       ],
       function (
           $,
           modal,
           alert,
           confirmation
       ) {
    var dataForm = $('#create-goals');
    dataForm.mage('validation', {});
    var goalBaseUrl = $("#goal_base_url").val();
    var adminTackUrl = $("#track_base_url").val();
    var goalBaseDeleteUrl = '<?= /* @noEscape */  $goalBaseDeleteUrl;?>'
    $("#wk-track-type").on('change',function(){
        $('.wktrackurl').addClass('no-display');
        $('.wktrackcond').addClass('no-display');
        $('.wkcssselector').addClass('no-display');
        var showLoader=true;
        var trackTypeId = $(this).val();
        if (typeof(trackTypeId) != "undefined") {
            var showLoader=true;
            var trackType = 'trackTypeId='+ trackTypeId;
                $.ajax({
                    showLoader: true,
                    url: adminTackUrl,
                    data: trackType,
                    type: "POST",
                    dataType: 'json'
                    }).done(function (data) {
                        if(data.success == true) {
                            $('.tracks').html(data.value) ;
                       }
                });
        }
    });
   
     $(".col-edit").on("click",function(){
        var goalEntityId = $(this).closest('tr').find(".col-entity_id").text();
        if(goalEntityId !== null) {
            var goalEntityId = 'goalEntityId='+ goalEntityId+'&requestType=display';;
            $.ajax({
                showLoader: true,
                url: goalBaseUrl,
                data: goalEntityId,
                type: "POST",
                dataType: 'json'
                }).done(function (data) {
                    if(data.success == true) {
                        $('.callfor-popup').modal('openModal');
                        $('.wktrackurl').addClass('no-display');
                        $('.wktrackcond').addClass('no-display');
                        $('.wkcssselector').addClass('no-display');
                        var dataArray = data.value;
                        $("#goal_name").val(dataArray.goal_name);
                        $("#goal_description").val(dataArray.goal_description);
                        $("#wk-track-type").val(dataArray.track_type_id);
                        $("#wk-track-type").trigger('change');
                        setTimeout(function () {
                            $('#tracks option[value='+dataArray.tracks+']').attr('selected','selected');
                             $("#tracks").val(dataArray.tracks);
                        }, 2500);
                        if(dataArray.url != "") {
                            $('.wktrackurl').removeClass('no-display');
                            $('.wktrackcond').removeClass('no-display');
                            $('.wkcssselector').addClass('no-display');
                            $("#url").val(dataArray.url);
                            $("#conditions").val(dataArray.conditions);
                        }
                        if(dataArray.css_property != "") {
                            $('.wkcssselector').removeClass('no-display');
                            $('.wktrackurl').addClass('no-display');
                            $('.wktrackcond').addClass('no-display');
                            $("#css_property").val(dataArray.css_property);
                        }
                        
                        $("#edit_goal_id").val(dataArray.entity_id);
                    }
            });
        }

    });
        $(".col-delete").on("click",function(){
        var goalEntityId = $(this).closest('tr').find(".col-entity_id").text();
        if(goalEntityId !== null) {
            var goalEntityId = 'goalEntityId='+ goalEntityId+'&requestType=delete';
            confirmation({
            title: 'Confirm Delete?',
            content: 'Do you want to delete this record?',
            actions: {
                confirm: function () {
                    $.ajax({
                            showLoader: true,
                            url: goalBaseDeleteUrl,
                            data: goalEntityId,
                            type: "POST",
                            dataType: 'json'
                            }).done(function (data) {
                                if(data.success == true) {
                                    window.location.reload();
                                }
                        });
                },

                cancel: function () {
                    return false;
                }
            }
        });
        }

    });
    $('.tracks').on('change', function(){
        var optionId = $(this).val();
        var optionVal = $('.tracks option:selected').text();
        if(optionVal == 'Track Pages Visit on') {
            $('.wktrackurl').removeClass('no-display');
            $('.wktrackcond').removeClass('no-display');
        } else if(optionVal == 'Click on element') {
            $('.wkcssselector').removeClass('no-display');
            $('.wktrackurl').addClass('no-display');
            $('.wktrackcond').addClass('no-display');
        } else {
            $('.wktrackurl').addClass('no-display');
            $('.wktrackcond').addClass('no-display');
            $('.wkcssselector').addClass('no-display');
        }
   });
        var modaloption = {
    type: 'slide',
    responsive: true,
    innerScroll: true,
    clickableOverlay: true,
    title: 'Add Goals',
    buttons: [{
     text: $.mage.__('Submit'),
     class: 'button wk-button-goals primary',
     click: function () {
         $('#create-goals').submit();
         form = $('#create-goals');
         form.mage('validation', {});
         $.ajax({
         type:"POST",
         url:form.attr("action"),
         async:false,
         data:$("#create-goals").serialize(),//only input
         success: function(response){
             if(response.success == true) {
                $('[data-message]').removeClass('no-display');
                $('[data-message]').text(response.value);
                window.location.reload();
             } else {
                alert({
                       title: 'Message',
                       content: response.value,
                       actions: {
                           always: function(){}
                       }
                    });
             }
            
         }
     });
     }
 }]
};
           var callforoption = modal(modaloption, $('.callfor-popup'));
          $('.abtest-goals').on('click',function() {
            $('.callfor-popup').modal('openModal');
          });

       }
   );
</script>
