<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_AbTesting
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$goalsDataOnVariantId= [];
$testId = $block->getRequest()->getParam('id');
$variantsActiveOnTest = $block->getAllVariantIdOnTestId($testId);

if (!empty($variantsActiveOnTest)) {
    $goalsDataOnVariantId = array_values($block->getGoalsDataOnVariant($variantsActiveOnTest));
    $prepareGraphData = json_encode($goalsDataOnVariantId);
}
$getGoalsOnTestId = $block->getAllGoalsOnTestId($testId);
?>
<style>
    .dates-filters-div{display:inline-block;float:right}
    .wk-inline-div {display:inline-block}
    .variant-reports-section{margin-top:30px;}
    .unique-variant-left {float:left;width:50%;}
    .unique-variant-right {float:right;width:50%;}
    .wk-variant-gp-name {color:#f36daa;font-weight:700;}
</style>
<?php if (empty($goalsDataOnVariantId)) {?>
    <p><?= /* @noEscape */ __('No Data Available On Test case to show Reports')?></p>
<?php } else {?>
<div class="abtest-report-section">
    <div class="note wk-inline-div" data-role="reports-info">
        <?= /* @noEscape */ $block->escapeHtml(__('Check insights for your business'));?>
    </div>
    <div class="dates-filters-div">
        <div class="field overview required" id="date-range">
           
        </div>
    </div>
    <div class="variant-reports-section">
        <div class="note variants-count" data-role="variants-count">
        </div>
    </div>
    <div class="individual-variant" style="width:100%">
            <?php
                $blockCount = 1;
            foreach ($variantsActiveOnTest as $variantId) {
                $variantName = $block->getVariantNameFromId($variantId);
                if ($blockCount % 2 == 0) {
                    $classVariantCss = 'unique-variant-right';
                } else {
                    $classVariantCss = 'unique-variant-left';
                }
                $goalsOnVariant = $block->getGoalsOnVariantId($variantId);
                ?>  
                 <div class ="<?= /* @noEscape */$classVariantCss;?> 
                 main-variant-graph-<?= /* @noEscape */ $variantId?>">
                 <h3 class="wk-variant-gp-name"><?= /* @noEscape */ $variantName;?></h3>
                 <?php if (!empty($goalsOnVariant)) {
                        foreach ($goalsOnVariant as $goalsData) {
                            $mainGoalName = $block->getMainGoalNameFromId($goalsData->getGoalId());
                            $goalTypeName = $block->getGoalNameFromId($goalsData->getGoalId())?>
                            <div class ="goals-info">
                                <strong><?= /* @noEscape */  __($mainGoalName)?>
                                 (<?= /* @noEscape */ $goalTypeName;?>)</strong>
                                <div style="width:100%;height:200px;"class="chart-on-goal-id-
                                <?= /* @noEscape */$goalsData->getGoalId()?>" 
                                id="wk-<?= /* @noEscape */$goalsData->getGoalId()?>
                                -<?= /* @noEscape */$variantId?>"></div>
                            </div>
                    <?php }
                 } else {
                     echo '<span> No data to show reports</span>';
                 }?>
                </div>
                <?php
                $blockCount ++;
            } ?>
           
    </div>
</div>
<?php }?>
<script>
require([
    'jquery',
    'mage/mage',
    'mage/calendar'
], function($){
    var reportbaseUrl = '<?= /* @noEscape */ $block->getUrl('abtesting/abtest/reportsajax')?>';
    $('*[id*=wk]:visible').each(function() {
        var dataId = $(this).attr('id');
        var result = dataId.split("-");
        var goalId = result[1];
        var variantId = result[2];
        if (typeof(variantId) != "undefined" && typeof(goalId) != "undefined") {
            var variantInfo = 'variantId='+ variantId+"&goalId="+goalId;
               $.ajax({
                    showLoader: true,
                    url: reportbaseUrl,
                    data: variantInfo,
                    type: "POST",
                    dataType: 'json',
                    async:false,
                    success: function(data) {
                        var arrVariantReport = []; 
                        if(data.success == true) {
                            var variantArrValue = data.value;
                            $.each(variantArrValue, function (index, value) {
                            arrVariantReport.push([value.year, value.month, value.day, value.track_number]);
                            }); 
                            google.charts.load('current', {packages: ['corechart', 'line']});
                            google.setOnLoadCallback(function() {
                                 drawLineColorsChart(arrVariantReport,goalId,variantId); 
                                 });
                      
                        }
                    }
            });
        }
    });
    $('#date-range').dateRange({
        buttonText: 'Select Date',
        from: {
            id: 'date-from'
        },
        to: {
            id: 'date-to'
        }
    });
});
</script>
<script>
function drawLineColorsChart(arrVariantReport,goalId,variantId) {
    var options = {
        hAxis: {
        title: 'Dates',
        format: 'MM/dd/yyyy',
        },
        vAxis: {
        title: 'Goals'
        },
        isStacked: true,
        legend: {position: 'top', maxLines: 3},
        colors: ['#f36daa', 'blue', '#3fc26b']
    };  
    var data = new google.visualization.DataTable();
    data.addColumn('date', 'Date');
    data.addColumn('number', 'Goals Data');
    for (var i = 0; i < arrVariantReport.length; i++) {
            data.addRow([new Date(arrVariantReport[i][0],arrVariantReport[i][1],
            arrVariantReport[i][2]),parseInt(arrVariantReport[i][3])]);   
    }
    var chart = new google.visualization.AreaChart(document.getElementById('wk-'+goalId+"-"+variantId));
    chart.draw(data, options);
}
</script>
