 <?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_AbTesting
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
 $testId = $block->getRequest()->getParam('id');
 $checkVariantExists = $block->checkVariantExistsForTestId($testId);
 if (empty($checkVariantExists)) {
     return false;
 }
    ?>
 <a class="wk-view-variant" href="" target="$_blank">
 <button>
    <span class="icon-pagebuilder-show"><?= /* @noEscape */ __('View')?></span>
</button>
</a>
<input type="hidden" name="wk-var-record-id" value =""/>
<script>
   require(
       [
           'jquery',
           'Magento_Ui/js/modal/modal',
           'mage/mage'
       ],
       function (
           $,
           modal
       ) {
        $('.wk-view-variant').on('click',function(){
            var variantValue = $(this).closest("tr.data-row").attr('data-repeat-index');
            var nameAttr = 'variants[dynamic_rows][dynamic_rows]['+variantValue+'][destination_url]';
            var currentUrl = $('input[name="'+nameAttr+'"]').val();
             $(this).closest("tr.data-row").find('.wk-view-variant').attr('href',currentUrl);
        });
          
       }
   );
</script>

