<?php
$quoteId = $this->getRequest()->getParam('quote_id'); 
$_items=$this->getCartdetailById($quoteId);
$_grandTotal=$this->getGrandTotalById($quoteId);
$_subTotal=$this->getSubTotalById($quoteId);
?>
<?php foreach ($_items as $item): ?>
    <table class="data-grid data-grid-draggable" data-role="grid">
       <thead>
            <tr>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" data-bind="i18n: label">Product Name</span>
                </th>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" data-bind="i18n: label">Qty</span>
                </th>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" data-bind="i18n: label">Unit Price</span>
                </th>
            </tr>
        </thead>
        <tbody>
            <tr class="data-row">
                <td>
                    <div class="data-grid-cell-content"><?php echo $item->getName();?></div>
                </td>
                <td>
                    <div class="data-grid-cell-content"><?php echo $item->getQty();?></div>
                </td> 
                <td>
                    <div class="data-grid-cell-content"><?php echo $item->getQty()*$item->getPrice()?></div>
                </td>
            </tr>
        </tbody>
    </table>
    <div style="padding-top: 15px; padding-right: 15px; float: right; ">
        <div><span style="font-weight:bold; ">Sub Total : <?php echo $_subTotal;?></span></div>
        <div><span style="font-weight:bold; ">Total : <?php echo $_grandTotal;?></span></div> 
    </div>
<?php endforeach;?>