<?php
// @codingStandardsIgnoreFile


/** @var $block Svea\Checkout\Block\Checkout */
$customerGroupId = $this->helper('\Magento\Customer\Helper\Session\CurrentCustomer')->getCustomer()->getGroupId();
if ($customerGroupId != 4) return;
?>

<div class="different-checkout-link">
    <a href="<?php echo $block->getUrl('checkout', ['_secure' => true]); ?>"
       title="<?= __('Use a different payment method') ?>">
        <?= __('Use a different payment method') ?>
    </a>
</div>
