<?php
// @codingStandardsIgnoreFile


/** @var $block Svea\Checkout\Block\Checkout */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('\Magento\Customer\Model\Session');
if ($customerSession->isLoggedIn()) {
   $customerGroupId = $customerSession->getCustomer()->getGroupId();
   if ($customerGroupId != 4) return;
} else {
   return;
}
?>

<div class="different-checkout-link">
    <a href="<?php echo $block->getUrl('checkout', ['_secure' => true]); ?>"
       title="<?= __('Use a different payment method') ?>">
        <?= __('Use a different payment method') ?>
    </a>
</div>
