<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_AbTesting
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$sampleCsv = $block->getSampleCsv();
?>
<div class="admin__field">
    <div class="admin__field-control">
        
        <a href="<?=/* @noEscape */  $sampleCsv;?>"><?= /* @noEscape */ __('Download Selector files')?></a>
    </div>
</div>