<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<?php if ($block->displayProductStockStatus()) :?>
    <?php if ($_product->isAvailable()) :?>
        <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span class="circle"></span>
            <span><?= $block->escapeHtml(__('In stock')) ?> - <?= $block->escapeHtml(__('Delivery from our warehouse in 1-3 days')) ?></span>
        </div>
    <?php else :?>
        <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span class="circle"></span>
            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$rule = $objectManager->create('Magento\SalesRule\Model\RuleFactory')->create()->load(2);
$item = $block->getProduct();
?>

<?php if($rule->getActions()->validate($item)):?>
    <strong>Shipping Icon Here</strong>
<?php endif;?>
