<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<?php if ($block->displayProductStockStatus()) :?>
    <?php if ($_product->isAvailable()) :?>
        <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span class="circle"></span>
            <span><?= $block->escapeHtml(__('In stock')) ?> - <?= $block->escapeHtml(__('- fast delivery')) ?></span>
        </div>
    <?php else :?>
        <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span class="circle"></span>
            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
            <span><?= $block->escapeHtml(__('arrives August 27th. You can pre-book below!')) ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$freeShippingAmount = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('carriers/freeshipping/free_shipping_subtotal');
?>

<?php if($freeShippingAmount):?>
    <div class="shipping-box">
        <img src="<?= $this->getViewFileUrl('Codazon_QuickShop::images/ship.png'); ?>">
        <strong><?= $block->escapeHtml(__('Free shipping over NOK ' . $freeShippingAmount)) ?></strong>
    </div>
<?php endif;?>
