<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
    $product = $block->getProduct();
    $productUrl = $product->getProductUrl();        
?>

<a class="qs_link_product_page action primary tocart"  
    href="<?php echo $productUrl ?>">
    <span><?php /* @escapeNotVerified */ echo __('Go to product page') ?></span>
</a>